Default: &defaults
  database: inmanis.sqlite3
  poolsize: 10

Development:
  <<: *defaults

Testing:
  database: inmanis_test.sqlite3
  <<: *defaults

Staging:
  database: inmanis_staging.sqlite3
  poolsize: 100
  <<: *defaults

Production:
  database: inmanis_production.sqlite3
  poolsize: 100
  <<: *defaults
